////////////////////////////////////////////////////////////////////////////
//
// FlashCap - Independent camera capture library.
// Copyright (c) Kouji Matsui (@kozy_kekyo, @kekyo@mastodon.cloud)
//
// Licensed under Apache-v2: https://opensource.org/licenses/Apache-2.0
//
////////////////////////////////////////////////////////////////////////////

#include <stdio.h>
#include <string.h>
#include <linux/videodev2.h>

int main(int argc, char* argv[])
{
    int bitCount = sizeof(unsigned long) * 32 / 4;

    char fileName[32];
    sprintf(fileName, "RequestCode%d.cs", bitCount);
    FILE* fp = fopen(fileName, "w");

    fprintf(fp, "// FlashCap - Independent camera capture library.\n");
    fprintf(fp, "// Copyright (c) Kouji Matsui (@kozy_kekyo, @kekyo@mastodon.cloud)\n");
    fprintf(fp, "// This is auto-generated by gen_request_code, do not edit.\n");
    fprintf(fp, "\n");
    fprintf(fp, "using System;\n");
    fprintf(fp, "\n");
    fprintf(fp, "namespace FlashCap.Internal.V4L2;\n");
    fprintf(fp, "\n");
    fprintf(fp, "internal sealed class RequestCode%d : RequestCode\n", bitCount);
    fprintf(fp, "{\n");
    fprintf(fp, "    public RequestCode%d()\n", bitCount);
    fprintf(fp, "    {\n");
    fprintf(fp, "    }\n");
    fprintf(fp, "\n");

    #define print_value(symbol) \
        fprintf(fp, "    public override UIntPtr " #symbol " => new UIntPtr(0x%08lx);\n", (unsigned long)(symbol))

    print_value(VIDIOC_QUERYCAP);
    print_value(VIDIOC_ENUMINPUT);
    print_value(VIDIOC_ENUM_FMT);
    print_value(VIDIOC_ENUM_FRAMESIZES);
    print_value(VIDIOC_ENUM_FRAMEINTERVALS);
    print_value(VIDIOC_S_FMT);
    print_value(VIDIOC_G_FMT);
    print_value(VIDIOC_REQBUFS);
    print_value(VIDIOC_QUERYBUF);
    print_value(VIDIOC_QBUF);
    print_value(VIDIOC_DQBUF);
    print_value(VIDIOC_STREAMON);
    print_value(VIDIOC_STREAMOFF);

    fprintf(fp, "}\n");

    fclose(fp);

    printf("%s generated.\n", fileName);

    return 0;
}
